import { supabase } from "@/lib/supabase";
import type {
  DetailImageJob,
  DetailImageType,
  DetailPageTemplateId,
} from "@/types/detailPage";

/**
 * AI detail-page image generation (client side).
 *
 * Each image is one call to the `generate-detail-image` edge function, which builds the
 * prompt server-side (supabase/functions/_shared/detailImagePrompt.ts), sends the creator's
 * design as the reference image to Gemini, stores the result in Supabase Storage and tracks
 * it in `generated_assets`. Images are requested independently with limited concurrency, so
 * a failed image never fails the page — it can be retried on its own.
 */

export type DetailImageSpec = {
  type: DetailImageType;
  number: string;
  label: string;
  description: string;
  /** Generated by default when building a page. */
  defaultOn: boolean;
};

export const DETAIL_IMAGE_SPECS: DetailImageSpec[] = [
  { type: "hero", number: "01", label: "HERO", description: "대표 이미지 · 메인 비주얼", defaultOn: true },
  { type: "product_front", number: "02", label: "CLEAN PRODUCT", description: "앞면 제품 단독 컷", defaultOn: true },
  { type: "product_back", number: "03", label: "BACK PRODUCT", description: "뒷면 제품 단독 컷", defaultOn: true },
  { type: "detail", number: "04", label: "DETAIL", description: "프린트·자수·그래픽 클로즈업", defaultOn: true },
  { type: "editorial", number: "05", label: "LOOKBOOK", description: "룩북 · 에디토리얼 컷", defaultOn: true },
  { type: "lifestyle", number: "06", label: "LIFESTYLE", description: "모델 착용 컷", defaultOn: true },
  { type: "mood", number: "07", label: "MOOD", description: "브랜드 무드 컷 (선택)", defaultOn: true },
  { type: "fabric", number: "08", label: "FABRIC", description: "원단 텍스처 클로즈업 (소재 정보가 있을 때)", defaultOn: false },
  { type: "flat_lay", number: "09", label: "FLAT LAY", description: "바닥·스튜디오에 자연스럽게 놓인 제품 컷", defaultOn: true },
  { type: "detail_print", number: "10", label: "PRINT DETAIL", description: "프린팅 클로즈업 (프린트가 있을 때)", defaultOn: false },
  { type: "detail_embroidery", number: "11", label: "EMBROIDERY", description: "자수 클로즈업 (자수가 있을 때)", defaultOn: false },
  { type: "detail_neck", number: "12", label: "COLLAR / HOOD", description: "카라·후드·넥라인 클로즈업", defaultOn: false },
  { type: "detail_cuff", number: "13", label: "SLEEVE / HEM", description: "소매·커프스·밑단 클로즈업", defaultOn: false },
  { type: "detail_stitch", number: "14", label: "STITCH", description: "봉제선 클로즈업", defaultOn: false },
  { type: "folded", number: "15", label: "FOLDED", description: "자연스럽게 접힌 제품 컷", defaultOn: false },
  { type: "mannequin", number: "16", label: "MANNEQUIN", description: "마네킹 착용 컷 (핏 확인)", defaultOn: false },
  { type: "texture_wide", number: "17", label: "TEXTURE", description: "원단 텍스처 와이드 크롭", defaultOn: false },
];

/** Aspect ratios accepted by generate-detail-image (Gemini image models). */
export const DETAIL_IMAGE_RATIOS = ["1:1", "2:3", "3:2", "3:4", "4:3", "4:5", "5:4", "9:16", "16:9", "21:9"] as const;

export const getDetailImageSpec = (type: DetailImageType) =>
  DETAIL_IMAGE_SPECS.find((spec) => spec.type === type) ?? DETAIL_IMAGE_SPECS[0];

const readFunctionError = async (error: unknown) => {
  const functionError = error as { message?: string; context?: Response };
  if (functionError?.context && typeof functionError.context.json === "function") {
    try {
      const payload = await functionError.context.json();
      if (typeof payload?.error === "string") return payload.error;
    } catch {
      // fall through
    }
  }
  return functionError?.message || "이미지 생성에 실패했습니다.";
};

export type GeneratedDetailImage = { assetId: string; url: string; model: string; ratio?: string };

/** Generates one image. Throws with a readable message on failure. */
export const requestDetailImage = async (input: {
  detailPageId: string;
  imageType: DetailImageType;
  style: DetailPageTemplateId;
  userInstruction?: string;
  /** Override the type's default ratio (art direction). Must be one of DETAIL_IMAGE_RATIOS. */
  aspectRatio?: string;
}): Promise<GeneratedDetailImage> => {
  const { data, error } = await supabase.functions.invoke("generate-detail-image", {
    body: {
      detailPageId: input.detailPageId,
      imageType: input.imageType,
      style: input.style,
      userInstruction: input.userInstruction || undefined,
      aspectRatio: input.aspectRatio || undefined,
    },
  });
  if (error) throw new Error(await readFunctionError(error));
  // (429: 하루/페이지 생성 한도 초과 메시지가 그대로 전달된다)
  if (!data?.url || !data?.assetId) throw new Error(data?.error || "이미지가 반환되지 않았습니다.");
  return { assetId: data.assetId, url: data.url, model: data.model, ratio: typeof data.aspectRatio === "string" ? data.aspectRatio : input.aspectRatio };
};

/** Runs `worker` over `items` with at most `limit` in flight. */
export const runWithConcurrency = async <T,>(items: T[], limit: number, worker: (item: T) => Promise<void>) => {
  const queue = [...items];
  const runners = Array.from({ length: Math.min(limit, queue.length) }, async () => {
    while (queue.length) {
      const item = queue.shift()!;
      await worker(item);
    }
  });
  await Promise.all(runners);
};

type AssetRow = {
  id: string;
  image_type: DetailImageType;
  generation_status: DetailImageJob["status"];
  generated_image: string | null;
  error_message: string | null;
  created_at: string;
  updated_at: string;
};

const STALE_GENERATING_MS = 6 * 60 * 1000;

/**
 * Latest generation per image type for a page, so status survives a refresh. A row stuck in
 * "generating" for minutes (tab closed and the function timed out) is reported as failed.
 */
export const fetchLatestImageJobs = async (detailPageId: string): Promise<Partial<Record<DetailImageType, DetailImageJob>>> => {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const { data, error } = await (supabase as any)
    .from("generated_assets")
    .select("id, image_type, generation_status, generated_image, error_message, created_at, updated_at")
    .eq("detail_page_id", detailPageId)
    .order("created_at", { ascending: false })
    .limit(80);
  if (error || !Array.isArray(data)) return {};
  const jobs: Partial<Record<DetailImageType, DetailImageJob>> = {};
  for (const row of data as AssetRow[]) {
    if (jobs[row.image_type]) continue;
    const stale = row.generation_status === "generating" && Date.now() - new Date(row.updated_at).getTime() > STALE_GENERATING_MS;
    jobs[row.image_type] = {
      imageType: row.image_type,
      status: stale ? "failed" : row.generation_status,
      assetId: row.id,
      url: row.generated_image,
      error: stale ? "생성 시간이 초과되었습니다." : row.error_message,
      updatedAt: row.updated_at,
    };
  }
  return jobs;
};
