import { useEffect, useState } from "react";
import { getMannequinPreset } from "@/lib/mannequin-presets";
import { MultiAngleViewer } from "@/components/visualization/MultiAngleViewer";
import { RotationViewer } from "@/components/visualization/RotationViewer";
import { useMultiAngleFrames } from "@/hooks/useMultiAngleFrames";
import type { CharacterGender, MannequinSize } from "@/types/closet";

interface DressingCanvasProps {
  character: CharacterGender;
  mannequinSize: MannequinSize;
  /** The latest AI-rendered "mannequin wearing the outfit" image. Falls back to the base preset. */
  renderedCharacterImage?: string | null;
  /** Shown as a small badge when the current render has no real garment measurements behind it. */
  isSimulated?: boolean;
  className?: string;
}

/**
 * The virtual mannequin canvas. `object-contain` guarantees the full body and every garment stays
 * visible and uncropped at any viewport size — never force-cropped or force-zoomed (mobile requirement).
 *
 * Once a fitting render exists, the canvas itself becomes a drag-to-rotate 360° viewer: the currently
 * worn garments are never regenerated by rotating — dragging only swaps between a fixed set of
 * pre-rendered angle frames captured once (lazily, on first interaction) from the exact same fitting
 * image. See `useMultiAngleFrames` / `generate-multi-angle` for how that identity lock is enforced.
 */
export const DressingCanvas = ({
  character,
  mannequinSize,
  renderedCharacterImage,
  isSimulated,
  className = "",
}: DressingCanvasProps) => {
  const preset = getMannequinPreset(character, mannequinSize);
  const displayImage = renderedCharacterImage || preset.previewImage;
  const [index, setIndex] = useState(0);
  const { frames, loading, ensure } = useMultiAngleFrames(renderedCharacterImage, "fitting");

  useEffect(() => {
    setIndex(0);
  }, [renderedCharacterImage]);

  return (
    <div className={`relative aspect-[3/4] w-full overflow-hidden rounded-[1.75rem] bg-gradient-to-b from-[#f4f0ea] to-[#ece5db] ${className}`}>
      {renderedCharacterImage ? (
        <RotationViewer
          frames={frames}
          index={index}
          onIndexChange={setIndex}
          fallbackImageUrl={displayImage}
          altText={preset.label}
          loading={loading}
          onDragIntent={ensure}
          className="absolute inset-0 h-full w-full"
          imgClassName="object-contain p-6"
          zoomEnabled
          wheelZoomRequiresCtrl
          hintStorageKey="brander-360-mannequin-hint-seen"
          hintPositionClassName={isSimulated ? "bottom-14" : "bottom-3"}
          loadingPositionClassName="left-3 top-3"
        />
      ) : (
        <img
          key={displayImage}
          src={displayImage}
          alt={preset.label}
          className="absolute inset-0 h-full w-full object-contain p-6"
        />
      )}
      {renderedCharacterImage && (
        <div className="absolute right-3 top-3 z-20 sm:right-4 sm:top-4">
          <MultiAngleViewer
            sourceImageUrl={renderedCharacterImage}
            mode="fitting"
            triggerLabel="360° 크게 보기"
            className="h-9 bg-white/95 px-3 text-xs"
          />
        </div>
      )}
      {renderedCharacterImage && isSimulated && (
        <span className="absolute bottom-3 left-3 right-3 z-10 rounded-xl bg-stone-950/80 px-3 py-2 text-center text-[11px] font-semibold leading-4 text-white">
          본 이미지는 선택한 체형과 핏 정보를 기반으로 생성된 AI 시뮬레이션이며, 실제 착용 결과와 차이가 있을 수 있습니다.
        </span>
      )}
    </div>
  );
};
