alter table public.site_visit_sessions
  add column if not exists lead_code text,
  add column if not exists lead_name text,
  add column if not exists lead_channel text,
  add column if not exists utm_source text,
  add column if not exists utm_medium text,
  add column if not exists utm_campaign text,
  add column if not exists utm_content text,
  add column if not exists last_event_name text;

create index if not exists site_visit_sessions_lead_code_idx
  on public.site_visit_sessions (lead_code, last_seen_at desc)
  where lead_code is not null;

create table if not exists public.sales_tracking_links (
  id uuid primary key default gen_random_uuid(),
  lead_code text not null unique,
  lead_name text not null,
  channel text not null default 'direct',
  destination_path text not null default '/',
  created_by uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  is_active boolean not null default true,
  click_count integer not null default 0 check (click_count >= 0),
  last_clicked_at timestamptz
);

create index if not exists sales_tracking_links_created_at_idx
  on public.sales_tracking_links (created_at desc);

alter table public.sales_tracking_links enable row level security;
revoke all on table public.sales_tracking_links from anon, authenticated;

create table if not exists public.site_visit_events (
  id bigint generated by default as identity primary key,
  session_id uuid not null references public.site_visit_sessions(session_id) on delete cascade,
  visitor_id uuid not null,
  user_id uuid references auth.users(id) on delete set null,
  event_name text not null,
  path text not null default '/',
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint site_visit_events_event_name_length check (char_length(event_name) between 1 and 80),
  constraint site_visit_events_path_length check (char_length(path) <= 300)
);

create index if not exists site_visit_events_session_created_idx
  on public.site_visit_events (session_id, created_at desc);

create index if not exists site_visit_events_user_created_idx
  on public.site_visit_events (user_id, created_at desc)
  where user_id is not null;

alter table public.site_visit_events enable row level security;
revoke all on table public.site_visit_events from anon, authenticated;

drop function if exists public.track_site_visit(uuid, uuid, text, text, text, text, boolean);

create or replace function public.track_site_visit(
  p_session_id uuid,
  p_visitor_id uuid,
  p_path text,
  p_referrer text default null,
  p_device_type text default 'unknown',
  p_browser text default 'unknown',
  p_is_page_view boolean default true,
  p_lead_code text default null,
  p_utm_source text default null,
  p_utm_medium text default null,
  p_utm_campaign text default null,
  p_utm_content text default null
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_path text := left(coalesce(nullif(trim(p_path), ''), '/'), 300);
  v_referrer text := nullif(left(trim(coalesce(p_referrer, '')), 500), '');
  v_device_type text := case
    when p_device_type in ('desktop', 'mobile', 'tablet') then p_device_type
    else 'unknown'
  end;
  v_browser text := left(coalesce(nullif(trim(p_browser), ''), 'unknown'), 50);
  v_lead_code text := nullif(left(trim(coalesce(p_lead_code, '')), 64), '');
  v_lead_name text;
  v_lead_channel text;
  v_utm_source text := nullif(left(trim(coalesce(p_utm_source, '')), 100), '');
  v_utm_medium text := nullif(left(trim(coalesce(p_utm_medium, '')), 100), '');
  v_utm_campaign text := nullif(left(trim(coalesce(p_utm_campaign, '')), 150), '');
  v_utm_content text := nullif(left(trim(coalesce(p_utm_content, '')), 150), '');
  v_is_new_session boolean;
begin
  if p_session_id is null or p_visitor_id is null then
    return;
  end if;

  if v_user_id is not null and public.is_admin(v_user_id) then
    delete from public.site_visit_sessions
    where visitor_id = p_visitor_id
      and user_id is null;
    return;
  end if;

  if v_lead_code is not null then
    select tracking.lead_name, tracking.channel
    into v_lead_name, v_lead_channel
    from public.sales_tracking_links tracking
    where tracking.lead_code = v_lead_code
      and tracking.is_active
    limit 1;

    if v_lead_name is null then
      v_lead_code := null;
    end if;
  end if;

  select not exists (
    select 1
    from public.site_visit_sessions existing
    where existing.session_id = p_session_id
  ) into v_is_new_session;

  insert into public.site_visit_sessions (
    session_id,
    visitor_id,
    user_id,
    entry_path,
    last_path,
    referrer,
    device_type,
    browser,
    page_view_count,
    lead_code,
    lead_name,
    lead_channel,
    utm_source,
    utm_medium,
    utm_campaign,
    utm_content,
    last_event_name
  ) values (
    p_session_id,
    p_visitor_id,
    v_user_id,
    v_path,
    v_path,
    v_referrer,
    v_device_type,
    v_browser,
    case when coalesce(p_is_page_view, true) then 1 else 0 end,
    v_lead_code,
    v_lead_name,
    v_lead_channel,
    v_utm_source,
    v_utm_medium,
    v_utm_campaign,
    v_utm_content,
    case when coalesce(p_is_page_view, true) then 'page_view' else null end
  )
  on conflict (session_id) do update
  set
    user_id = coalesce(v_user_id, site_visit_sessions.user_id),
    last_seen_at = now(),
    last_path = v_path,
    device_type = v_device_type,
    browser = v_browser,
    page_view_count = site_visit_sessions.page_view_count
      + case when coalesce(p_is_page_view, true) then 1 else 0 end,
    lead_code = coalesce(v_lead_code, site_visit_sessions.lead_code),
    lead_name = coalesce(v_lead_name, site_visit_sessions.lead_name),
    lead_channel = coalesce(v_lead_channel, site_visit_sessions.lead_channel),
    utm_source = coalesce(site_visit_sessions.utm_source, v_utm_source),
    utm_medium = coalesce(site_visit_sessions.utm_medium, v_utm_medium),
    utm_campaign = coalesce(site_visit_sessions.utm_campaign, v_utm_campaign),
    utm_content = coalesce(site_visit_sessions.utm_content, v_utm_content),
    last_event_name = case
      when coalesce(p_is_page_view, true) then 'page_view'
      else site_visit_sessions.last_event_name
    end;

  if v_user_id is not null then
    update public.site_visit_sessions
    set user_id = v_user_id
    where visitor_id = p_visitor_id
      and user_id is null;

    update public.site_visit_events
    set user_id = v_user_id
    where visitor_id = p_visitor_id
      and user_id is null;
  end if;

  if v_is_new_session and v_lead_code is not null then
    update public.sales_tracking_links
    set
      click_count = click_count + 1,
      last_clicked_at = now()
    where lead_code = v_lead_code;
  end if;

  if coalesce(p_is_page_view, true) then
    insert into public.site_visit_events (
      session_id,
      visitor_id,
      user_id,
      event_name,
      path,
      metadata
    ) values (
      p_session_id,
      p_visitor_id,
      v_user_id,
      'page_view',
      v_path,
      jsonb_strip_nulls(jsonb_build_object(
        'utm_source', v_utm_source,
        'utm_medium', v_utm_medium,
        'utm_campaign', v_utm_campaign
      ))
    );
  end if;

  if v_is_new_session and random() < 0.02 then
    delete from public.site_visit_sessions
    where last_seen_at < now() - interval '180 days';
  end if;
end;
$$;

revoke all on function public.track_site_visit(
  uuid, uuid, text, text, text, text, boolean, text, text, text, text, text
) from public;
grant execute on function public.track_site_visit(
  uuid, uuid, text, text, text, text, boolean, text, text, text, text, text
) to anon, authenticated;

create or replace function public.track_site_event(
  p_session_id uuid,
  p_visitor_id uuid,
  p_event_name text,
  p_path text default '/',
  p_metadata jsonb default '{}'::jsonb
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_event_name text := left(trim(coalesce(p_event_name, '')), 80);
  v_path text := left(coalesce(nullif(trim(p_path), ''), '/'), 300);
  v_metadata jsonb := coalesce(p_metadata, '{}'::jsonb);
  v_allowed_events text[] := array[
    'design_generated',
    'design_modified',
    'funding_draft_created',
    'production_request_submitted',
    'design_quote_submitted',
    'fabric_swatch_submitted',
    'funding_checkout_started'
  ];
begin
  if p_session_id is null
    or p_visitor_id is null
    or not (v_event_name = any(v_allowed_events)) then
    return;
  end if;

  if v_user_id is not null and public.is_admin(v_user_id) then
    return;
  end if;

  if octet_length(v_metadata::text) > 2000 then
    v_metadata := '{}'::jsonb;
  end if;

  if not exists (
    select 1
    from public.site_visit_sessions session
    where session.session_id = p_session_id
      and session.visitor_id = p_visitor_id
  ) then
    return;
  end if;

  insert into public.site_visit_events (
    session_id,
    visitor_id,
    user_id,
    event_name,
    path,
    metadata
  ) values (
    p_session_id,
    p_visitor_id,
    v_user_id,
    v_event_name,
    v_path,
    v_metadata
  );

  update public.site_visit_sessions
  set
    user_id = coalesce(v_user_id, user_id),
    last_seen_at = now(),
    last_path = v_path,
    last_event_name = v_event_name
  where session_id = p_session_id
    and visitor_id = p_visitor_id;
end;
$$;

revoke all on function public.track_site_event(uuid, uuid, text, text, jsonb) from public;
grant execute on function public.track_site_event(uuid, uuid, text, text, jsonb)
  to anon, authenticated;

create or replace function public.create_admin_sales_tracking_link(
  p_lead_name text,
  p_channel text default 'direct',
  p_destination_path text default '/'
)
returns table (
  id uuid,
  lead_code text,
  lead_name text,
  channel text,
  destination_path text,
  created_at timestamptz,
  is_active boolean,
  click_count integer,
  last_clicked_at timestamptz
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_lead_name text := nullif(left(trim(coalesce(p_lead_name, '')), 100), '');
  v_channel text := coalesce(nullif(left(trim(coalesce(p_channel, '')), 50), ''), 'direct');
  v_destination_path text := left(coalesce(nullif(trim(p_destination_path), ''), '/'), 200);
  v_lead_code text := 'br_' || left(replace(gen_random_uuid()::text, '-', ''), 16);
begin
  if auth.uid() is null or not public.is_admin(auth.uid()) then
    raise exception '관리자 권한이 필요합니다.';
  end if;

  if v_lead_name is null then
    raise exception '고객명 또는 브랜드명을 입력해주세요.';
  end if;

  if left(v_destination_path, 1) <> '/' or left(v_destination_path, 2) = '//' then
    raise exception '이동 경로는 /로 시작하는 사이트 내부 경로여야 합니다.';
  end if;

  return query
  insert into public.sales_tracking_links (
    lead_code,
    lead_name,
    channel,
    destination_path,
    created_by
  ) values (
    v_lead_code,
    v_lead_name,
    v_channel,
    v_destination_path,
    auth.uid()
  )
  returning
    sales_tracking_links.id,
    sales_tracking_links.lead_code,
    sales_tracking_links.lead_name,
    sales_tracking_links.channel,
    sales_tracking_links.destination_path,
    sales_tracking_links.created_at,
    sales_tracking_links.is_active,
    sales_tracking_links.click_count,
    sales_tracking_links.last_clicked_at;
end;
$$;

revoke all on function public.create_admin_sales_tracking_link(text, text, text) from public;
grant execute on function public.create_admin_sales_tracking_link(text, text, text)
  to authenticated;

create or replace function public.get_admin_sales_tracking_links()
returns table (
  id uuid,
  lead_code text,
  lead_name text,
  channel text,
  destination_path text,
  created_at timestamptz,
  is_active boolean,
  click_count integer,
  last_clicked_at timestamptz
)
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is null or not public.is_admin(auth.uid()) then
    raise exception '관리자 권한이 필요합니다.';
  end if;

  return query
  select
    tracking.id,
    tracking.lead_code,
    tracking.lead_name,
    tracking.channel,
    tracking.destination_path,
    tracking.created_at,
    tracking.is_active,
    tracking.click_count,
    tracking.last_clicked_at
  from public.sales_tracking_links tracking
  order by tracking.created_at desc;
end;
$$;

revoke all on function public.get_admin_sales_tracking_links() from public;
grant execute on function public.get_admin_sales_tracking_links() to authenticated;

create or replace function public.set_admin_sales_tracking_link_active(
  p_id uuid,
  p_is_active boolean
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is null or not public.is_admin(auth.uid()) then
    raise exception '관리자 권한이 필요합니다.';
  end if;

  update public.sales_tracking_links
  set is_active = coalesce(p_is_active, false)
  where id = p_id;
end;
$$;

revoke all on function public.set_admin_sales_tracking_link_active(uuid, boolean) from public;
grant execute on function public.set_admin_sales_tracking_link_active(uuid, boolean)
  to authenticated;

create or replace function public.get_admin_customer_overview()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_today_start timestamptz :=
    (date_trunc('day', now() at time zone 'Asia/Seoul') at time zone 'Asia/Seoul');
  v_registered_customers bigint;
  v_today_visitors bigint;
  v_active_now bigint;
  v_repeat_visitors bigint;
  v_confirmed_today bigint;
  v_lead_today bigint;
  v_anonymous_today bigint;
begin
  if auth.uid() is null or not public.is_admin(auth.uid()) then
    raise exception '관리자 권한이 필요합니다.';
  end if;

  select count(*)
  into v_registered_customers
  from auth.users auth_user
  where not public.is_admin(auth_user.id);

  select count(distinct visitor_id)
  into v_today_visitors
  from public.site_visit_sessions
  where last_seen_at >= v_today_start;

  select count(distinct visitor_id)
  into v_active_now
  from public.site_visit_sessions
  where last_seen_at >= now() - interval '5 minutes';

  select count(*)
  into v_repeat_visitors
  from (
    select visitor_id
    from public.site_visit_sessions
    group by visitor_id
    having count(*) >= 2
  ) repeated;

  select count(distinct visitor_id)
  into v_confirmed_today
  from public.site_visit_sessions
  where last_seen_at >= v_today_start
    and user_id is not null;

  select count(distinct visitor_id)
  into v_lead_today
  from public.site_visit_sessions
  where last_seen_at >= v_today_start
    and user_id is null
    and lead_code is not null;

  select count(distinct visitor_id)
  into v_anonymous_today
  from public.site_visit_sessions
  where last_seen_at >= v_today_start
    and user_id is null
    and lead_code is null;

  return jsonb_build_object(
    'registered_customers', v_registered_customers,
    'today_visitors', v_today_visitors,
    'active_now', v_active_now,
    'repeat_visitors', v_repeat_visitors,
    'confirmed_today', v_confirmed_today,
    'lead_today', v_lead_today,
    'anonymous_today', v_anonymous_today
  );
end;
$$;

revoke all on function public.get_admin_customer_overview() from public;
grant execute on function public.get_admin_customer_overview() to authenticated;

drop function if exists public.get_admin_visit_sessions(integer);

create or replace function public.get_admin_visit_sessions(
  p_limit integer default 300,
  p_period text default 'today'
)
returns table (
  session_id uuid,
  visitor_id uuid,
  user_id uuid,
  email text,
  display_name text,
  account_type text,
  identity_status text,
  lead_code text,
  lead_name text,
  lead_channel text,
  started_at timestamptz,
  last_seen_at timestamptz,
  entry_path text,
  last_path text,
  referrer text,
  utm_source text,
  utm_medium text,
  utm_campaign text,
  utm_content text,
  device_type text,
  browser text,
  page_view_count integer,
  event_count bigint,
  last_event_name text,
  journey jsonb,
  is_active boolean
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_start timestamptz;
begin
  if auth.uid() is null or not public.is_admin(auth.uid()) then
    raise exception '관리자 권한이 필요합니다.';
  end if;

  v_start := case p_period
    when 'today' then
      (date_trunc('day', now() at time zone 'Asia/Seoul') at time zone 'Asia/Seoul')
    when '7d' then now() - interval '7 days'
    else null
  end;

  return query
  select
    visit.session_id,
    visit.visitor_id,
    visit.user_id,
    auth_user.email::text,
    coalesce(
      nullif(profile.brand_name, ''),
      nullif(profile.username, ''),
      nullif(profile.full_name, ''),
      auth_user.email::text,
      nullif(visit.lead_name, ''),
      '익명 방문자 #' || upper(left(visit.visitor_id::text, 4))
    ) as display_name,
    profile.account_type,
    case
      when visit.user_id is not null then 'confirmed'
      when visit.lead_code is not null then 'lead'
      else 'anonymous'
    end as identity_status,
    visit.lead_code,
    visit.lead_name,
    visit.lead_channel,
    visit.started_at,
    visit.last_seen_at,
    visit.entry_path,
    visit.last_path,
    visit.referrer,
    visit.utm_source,
    visit.utm_medium,
    visit.utm_campaign,
    visit.utm_content,
    visit.device_type,
    visit.browser,
    visit.page_view_count,
    coalesce(event_total.event_count, 0),
    coalesce(event_total.last_event_name, visit.last_event_name),
    coalesce(event_journey.journey, '[]'::jsonb),
    visit.last_seen_at >= now() - interval '5 minutes' as is_active
  from public.site_visit_sessions visit
  left join auth.users auth_user on auth_user.id = visit.user_id
  left join public.profiles profile on profile.id = visit.user_id
  left join lateral (
    select
      count(*)::bigint as event_count,
      (array_agg(event.event_name order by event.created_at desc))[1] as last_event_name
    from public.site_visit_events event
    where event.session_id = visit.session_id
  ) event_total on true
  left join lateral (
    select jsonb_agg(
      jsonb_build_object(
        'event_name', recent.event_name,
        'path', recent.path,
        'metadata', recent.metadata,
        'created_at', recent.created_at
      ) order by recent.created_at asc
    ) as journey
    from (
      select event.event_name, event.path, event.metadata, event.created_at
      from public.site_visit_events event
      where event.session_id = visit.session_id
      order by event.created_at desc
      limit 20
    ) recent
  ) event_journey on true
  where v_start is null or visit.last_seen_at >= v_start
  order by visit.last_seen_at desc
  limit least(greatest(coalesce(p_limit, 300), 1), 1000);
end;
$$;

revoke all on function public.get_admin_visit_sessions(integer, text) from public;
grant execute on function public.get_admin_visit_sessions(integer, text)
  to authenticated;
